# Generated by Django 6.0.2 on 2026-02-25 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('careapp', '0002_myappointments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myappointments',
            old_name='departments',
            new_name='department',
        ),
    ]
